### PR TITLE
Initial code

### PR DESCRIPTION
**Pull request by njam**
TODO:
- [ ] maxFrequency parameter to not open further issues in a given time window -> https://github.com/cargomedia/loggly-github/issues/3
- [x] assignee parameter

### CODE REVIEW

**Comment by njam** [comment]
> loggly-github starts an HTTP server where Loggly can send alert postbacks to. For each new alert postback it will open a GitHub ticket.

@vogdb @tomaszdurka wdyt? please review.

**Comment by tomaszdurka** [comment]
Nice idea! There is nothing like that yet? 

- Can you configure ticket somehow? 
- Are there some *template-vars* you can use in url and pass content etc to be more specific? Probably there is no need for that.

**Comment by vogdb** [comment]
- quite dangerous to use privates `util._extend`
- there is no need in calling `done();` at the end of Config tests.
- test_helper.js is not needed

**Comment by vogdb** [comment]
Kind of odd that Loggly does not provide such a thing. Btw very good job, mr. Njam! :)

**Comment by njam** [comment]
> Can you configure ticket somehow?

Templating is a nice idea! -> https://github.com/cargomedia/loggly-github/issues/2

> quite dangerous to use privates util._extend

You can go ahead and use util._extends() if you want. It's not going anywhere any time soon.
https://github.com/nodejs/node-v0.x-archive/pull/4834#issuecomment-13981250

> test_helper.js is not needed

I understand requiring `mocha-sinon` in the test helper (for every test) installs some mocha hooks, to clean up the "sinon" environment after every test, `node_modules/mocha-sinon/mocha-sinon.js`:
```js
  beforeEach(function() {
    if (null == this.sinon) {
      this.sinon = sinon.sandbox.create();
    }
  });

[…]

  afterEach(function() {
    if (this.sinon && 'function' === typeof this.sinon.restore) {
      this.sinon.restore();
    }
  });
```
So I think it's useful?

> - there is no need in calling `done();` at the end of Config tests.

I've tried to remove both of the two `done()` calls in `test/config.js`. In both cases the test times out. Which one do you mean, and why is it not needed?

**Comment by vogdb** [comment]
Agree with everything except
> I've tried to remove both of the two `done()` calls in `test/config.js`. In both cases the test times out. Which one do you mean, and why is it not needed?

You should also delete `done` from arguments of `it` call.
```js
it('reads, parses and returns a valid config', function testSlash() {
```
instead of
```js
it('reads, parses and returns a valid config', function testSlash(done) {
```

**Comment by njam** [comment]
Aha! So if a test is completely synchronous `done()` can be omitted? Makes sense!

Please double check

**Comment by vogdb** [comment]
> Aha! So if a test is completely synchronous `done()` can be omitted?

Yes. lgtm

**Pull request merged**
