### PR TITLE
Don't open multiple tickets for same alert

### PR DESCRIPTION
**Pull request by njam**
List open tickets, and check if there is still one for the same alert, in that case don't open a new one.

### CODE REVIEW

**Comment by njam** [comment]
@vogdb please review

**Comment by vogdb** [comment]
- Why double quotes? `.expect("Internal Server Error\n", done);` `res.send("Internal Server Error\n");`
- We have a usual formatting for promises. Please adjust `startServer` according to it.

  ```js
    Promise.resolve()
      .then(function() {
        var data = JSON.parse(req.body);
        return validateAlertData(data);
      })
      .then(function(alert) {
  ```
- Shall we put `return` in `handleAlert` for consistency?

  ```js
    if (issue) {
      console.log(`Found an existing open issue (${user}/${repo}#${issue['number']}), skipping.`)
  ```

- I would recommend to use here `done`

  ```js
  it('creates a new issue', function() {
  ```

- Shouldn't we call `verify();` for all mocks in in `test/handler/github`?
- Why we return in `it('skips issue creation if an existing open issue is found'` ?

**Comment by njam** [comment]
@vogdb thanks, some of the specs were not really working :/
I'm using https://github.com/domenic/chai-as-promised/ now

Please review

**Comment by vogdb** [comment]
ok, lgtm

**Pull request merged**
