### PR TITLE
Increase maximum parseable body size

### PR DESCRIPTION
**Pull request by njam**
Default is 100kb

@vogdb or @tomaszdurka please review

### CODE REVIEW

**Comment by njam** [comment]
@vogdb or @tomaszdurka please review

**Comment by njam** [comment]
Closes #10

**Comment by vogdb** [comment]
I will review

**Comment by vogdb** [comment]
I don't see the usage of `var bigPayload` in tests. The rest is good.

**Comment by njam** [comment]
The assertion I'm interested here is that the request is processed successfully. If I would not change the limit the application would abort and an exception would be thrown (see https://github.com/cargomedia/loggly-github/issues/10).

**Comment by vogdb** [comment]
How it relates to the fact that `var bigPayload = 'x'.repeat(200 * 1000);` is not used and you duplicate the same data in
```js
var payload = {... 'big_data': 'x'.repeat(200 * 1000)};
```

**Comment by njam** [comment]
Oh, I wanted to use `bigPayload` in `payload`!
I clarified it a bit now.
Please review.

**Comment by vogdb** [comment]
a forced push :D cheater!

lgtm

**Pull request merged**
